### ISSUE TITLE
Faster replanting

### ISSUE THREAD

**Issue by Juru111** [Ryhon0/ReplanterPlus#3]
Hi!
Was using this mod on 1.0 and lately upgraded to 2.1.0 (alongside updating Minecraft).
With upgrade I notice much slower replanting with multiple crops with holding RMB than on v1.0.
Could there be an option to revert to faster planting or maybe way to configure it?

**Comment by Ryhon0** [comment]
1.20.2 seems to set the interaction delay to 4 ticks when using an item, this wasn't the case in 1.20.1, I've added a config screen with an option to adjust it in 2.2.0.
